// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srjpegylwguhyywxhtko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyanBlZ3lsd2d1aHl5d3hodGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NjMzMjYsImV4cCI6MjA1MjIzOTMyNn0.jHp8htMtdKn1bUUEki8trYzm7BqdgZy5DCENbnvu738";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);